/**
 * TipTap ResearchRef Extension
 *
 * Custom inline node that renders research reference indicators as
 * superscript numbers with hover cards showing source details.
 *
 * Parses <span class="ref-indicator" data-ref-id="..." data-ref-index="...">N</span>
 * from HTML content generated by the backend.
 */

import { Node, mergeAttributes } from '@tiptap/core'
import { ReactNodeViewRenderer } from '@tiptap/react'
import { ResearchRefNodeView } from '@/features/portfolio/components/editor/ResearchRefNodeView'

export interface ResearchRefOptions {
  HTMLAttributes: Record<string, unknown>
}

export const ResearchRef = Node.create<ResearchRefOptions>({
  name: 'researchRef',
  group: 'inline',
  inline: true,
  atom: true,
  selectable: true,
  draggable: false,

  addOptions() {
    return {
      HTMLAttributes: {},
    }
  },

  addAttributes() {
    return {
      refId: {
        default: null,
        parseHTML: (el: HTMLElement) => el.getAttribute('data-ref-id'),
        renderHTML: (attrs: Record<string, unknown>) => ({ 'data-ref-id': attrs.refId }),
      },
      refIndex: {
        default: null,
        parseHTML: (el: HTMLElement) => el.getAttribute('data-ref-index'),
        renderHTML: (attrs: Record<string, unknown>) => ({ 'data-ref-index': attrs.refIndex }),
      },
    }
  },

  parseHTML() {
    return [{ tag: 'span.ref-indicator[data-ref-id]' }]
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'span',
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
        class: 'ref-indicator',
        contenteditable: 'false',
      }),
      HTMLAttributes.refIndex || '',
    ]
  },

  addNodeView() {
    return ReactNodeViewRenderer(ResearchRefNodeView)
  },
})
