export { ReferenceCard } from './ReferenceCard'
export { ReferenceDetailSheet } from './ReferenceDetailSheet'
export { ReferenceUploadDialog } from './ReferenceUploadDialog'
export { FileDropZone } from './FileDropZone'
export { PublicationUrlInput } from './PublicationUrlInput'
export { detectPlatform, PLATFORM_META } from './platform-utils'
